B1
elong0527/forestly pull request #12
Opened 2021-03-05 14:46 UTC by YitaoLiu1996

2021-03-05 14:49 UTC, elong0527 commented on R/tidy_observation.R
> +#' @param observation_from
please add explanation of each variable in @param.

2021-03-12 15:06 UTC, elong0527 requested changes
It is a good start! I provide some examples for you to refer. They are from other function, you shall not directly copy and paste but just refer them to document yours.

2021-03-12 15:06 UTC, elong0527 commented on R/tidy_observation.R
> +#'
This is a good start. We shall make the variable  definition more informative to clarify the type of variable. 

Please refer example below and try to follow similar style. 

Sentence 1: define variable type
Sentence 2: explain what's the meaning of the variable
Sentence 3 (optional): explain what's the default value


```
#' @param population_from A data frame to obtain population level variables.
#'                        Typically an `adsl` dataset.
#'                        It is the source of variables mentioned in
#'                        `population_where`, `treatment_var`, `stratum_var` and `covariate_var`.
#' @param observation_from A data frame to obtain observation level variables.
#'                         Typically an `adtte` dataset for time-to-event analysis.
#'                         It is the source of variables mentioned in
#'                         `observation_where`, `start_date_var`, `end_date_var`, `censor_var`.
#' @param population_where A character string to define the criteria to select analysis population.
#' @param observation_where A character string to define the criteria to select analysis observation.
#' @param stratum_var A character string to define the variable of baseline stratum in `population_from`.
#'        Only one `stratum_var` is allowed.
```


@Yanping123DFEF  @mj719  @kyle9960 , you can follow similar style for your work

2021-03-12 15:06 UTC, elong0527 commented on R/tidy_observation.R
> +#' Select the Desired Observation
Please clarify more of what we are trying to achieve. 

What is "Desired Observation"?  You may refer example below

```
#' This function is used to prepare ADaM datasets (e.g. ADSL and ADTTE),
#' for time-to-event analysis. The function filter the population,
#' and then tidy the data as the standard time to event format. So the output
#' data will be easy to fit into the subsequent analysis functions.
```

2021-03-12 15:06 UTC, elong0527 commented on R/tidy_observation.R
> +#' @return a table of observation information
Return shall follow similar style:

what's the type of output?
if it is a data frame, what is the meaning of each variable in the data frame?

2021-03-20 01:09 UTC, elong0527 requested changes
Looks good. If you are OK with my suggestions below. Just accept them and I will approve it to complete this review.

2021-03-20 01:09 UTC, elong0527 commented on R/tidy_observation.R
> +#' This function is used to prepare the observation datasets for the use in function tidy_ae_table().
just add code formatting 
```suggestion
#' This function is used to prepare the observation datasets for the use in function `tidy_ae_table()`.
```

2021-03-20 01:09 UTC, elong0527 commented on R/tidy_observation.R
> +#' The function filter the 'adae' dataset, and define a 'treatment' in the dataset.
```suggestion
#' The function filter the `adae` dataset, and define proper treatment order in the dataset.
```

2021-03-20 01:09 UTC, elong0527 commented on R/tidy_observation.R
> +#'                         Typically an 'adae' dataset for time-to-event analysis.
```suggestion
#'                         Typically an `adae` dataset for time-to-event analysis.
```

2021-03-20 01:09 UTC, elong0527 commented on R/tidy_observation.R
> +#'                         'observation_where', 'start_date_var', 'end_date_var', 'censor_var'.
```suggestion
#'                         `observation_where`, `start_date_var`, `end_date_var`, `censor_var`.
```

2021-03-20 01:09 UTC, elong0527 commented on R/tidy_population.R
> +#' The function filter the 'adsl' dataset, and define a 'treatment' in the dataset.
```suggestion
#' The function filter the `adsl` dataset, and define proper treatment order in the dataset.
```

2021-03-20 01:09 UTC, elong0527 commented on R/tidy_population.R
> +#'                        'population_where', 'treatment_var', 'stratum_var' and 'covariate_var'.
```suggestion
#'                        `population_where`, `treatment_var`, `stratum_var` and `covariate_var`.
```

2021-03-20 01:09 UTC, elong0527 commented on R/tidy_population.R
> +#' @param treatment_order A vector of character strings that tells the function which rows of the table should be select, only if the values in "treatment" is in this vector.
```suggestion
#' @param treatment_order A vector of character strings that tells the 
#'                function which rows of the table should be select, 
#'                only if the values in "treatment" is in this vector.
```

2021-03-20 01:09 UTC, elong0527 commented on R/tidy_population.R
> +#' @param treatment_order A vector of character strings that tells the function which rows of the table should be select, only if the values in "treatment" is in this vector.
Break long line into multiple.

2021-03-24 20:04 UTC, YitaoLiu1996 commented
Hello Yilong,
I have made the changes according to your suggestions. Please review them.
Also, is there any reading that I could do to get ready for the
next meeting?


yilong zhang ***@***.***> 于2021年3月19日周五 下午9:09写道：

> ***@***.**** requested changes on this pull request.
>
> Looks good. If you are OK with my suggestions below. Just accept them and
> I will approve it to complete this review.
> ------------------------------
>
> In R/tidy_observation.R
> <https://github.com/elong0527/forestly/pull/12#discussion_r598039603>:
>
> > @@ -1,13 +1,76 @@
>
>  #' tidy_observation
>
>  #'
>
> -#' Select the Desired Observation
>
> +#' This function is used to prepare the observation datasets for the use in function tidy_ae_table().
>
>
> just add code formatting
> ⬇️ Suggested change
>
> -#' This function is used to prepare the observation datasets for the use in function tidy_ae_table().
>
> +#' This function is used to prepare the observation datasets for the use in function `tidy_ae_table()`.
>
>
> ------------------------------
>
> In R/tidy_observation.R
> <https://github.com/elong0527/forestly/pull/12#discussion_r598039684>:
>
> > @@ -1,13 +1,76 @@
>
>  #' tidy_observation
>
>  #'
>
> -#' Select the Desired Observation
>
> +#' This function is used to prepare the observation datasets for the use in function tidy_ae_table().
>
> +#' The function filter the 'adae' dataset, and define a 'treatment' in the dataset.
>
>
> ⬇️ Suggested change
>
> -#' The function filter the 'adae' dataset, and define a 'treatment' in the dataset.
>
> +#' The function filter the `adae` dataset, and define proper treatment order in the dataset.
>
>
> ------------------------------
>
> In R/tidy_observation.R
> <https://github.com/elong0527/forestly/pull/12#discussion_r598039754>:
>
> >  #'
>
> -#' @return a table of observation information
>
> +#' @param observation_from A data frame to obtain observation level variables.
>
> +#'                         Typically an 'adae' dataset for time-to-event analysis.
>
>
> ⬇️ Suggested change
>
> -#'                         Typically an 'adae' dataset for time-to-event analysis.
>
> +#'                         Typically an `adae` dataset for time-to-event analysis.
>
>
> ------------------------------
>
> In R/tidy_observation.R
> <https://github.com/elong0527/forestly/pull/12#discussion_r598039835>:
>
> >  #'
>
> -#' @return a table of observation information
>
> +#' @param observation_from A data frame to obtain observation level variables.
>
> +#'                         Typically an 'adae' dataset for time-to-event analysis.
>
> +#'                         It is the source of variables mentioned in
>
> +#'                         'observation_where', 'start_date_var', 'end_date_var', 'censor_var'.
>
>
> ⬇️ Suggested change
>
> -#'                         'observation_where', 'start_date_var', 'end_date_var', 'censor_var'.
>
> +#'                         `observation_where`, `start_date_var`, `end_date_var`, `censor_var`.
>
>
> ------------------------------
>
> In R/tidy_population.R
> <https://github.com/elong0527/forestly/pull/12#discussion_r598039887>:
>
> > @@ -1,15 +1,24 @@
>
>  #' tidy_population
>
>  #'
>
> -#' Get population level tidy data
>
> +#' This function is used to prepare the observation datasets for the use in function tidy_ae_table().
>
>
> ⬇️ Suggested change
>
> -#' This function is used to prepare the observation datasets for the use in function tidy_ae_table().
>
> +#' This function is used to prepare the observation datasets for the use in function `tidy_ae_table()`.
>
>
> ------------------------------
>
> In R/tidy_population.R
> <https://github.com/elong0527/forestly/pull/12#discussion_r598039927>:
>
> > @@ -1,15 +1,24 @@
>
>  #' tidy_population
>
>  #'
>
> -#' Get population level tidy data
>
> +#' This function is used to prepare the observation datasets for the use in function tidy_ae_table().
>
> +#' The function filter the 'adsl' dataset, and define a 'treatment' in the dataset.
>
>
> ⬇️ Suggested change
>
> -#' The function filter the 'adsl' dataset, and define a 'treatment' in the dataset.
>
> +#' The function filter the `adsl` dataset, and define proper treatment order in the dataset.
>
>
> ------------------------------
>
> In R/tidy_population.R
> <https://github.com/elong0527/forestly/pull/12#discussion_r598040006>:
>
> >  #'
>
> -#' @param population_from The input population level data table. For example, "subject level information" from the table "adsl".
>
> -#' @param population_where Tells the function which rows of the table should be select, according to the value of certain column. For example, select subset where "ITTFL=='Y'.
>
> -#' @param treatment_var The function will create a new column called "treatment" based on the column of this parameter. For example, the "treatment" column will be equal to "TRT01A".
>
> -#' @param treatment_order Tells the function which rows of the table should be select, only if the values in "treatment" is in this parameter. It also provide the label names of the treatments after turning them into factors. For example, include rows which treatment = "Placebo" and treatment = "Xanomeline High Dose", and change the factor labels into "Placebo" and "MK9999".
>
> -#' @param stratum_var The function will create a new column called "stratum" based on this parameter.
>
> +#' @param population_from A data frame to obtain population level variables.
>
> +#'                        Typically an 'adsl' dataset.
>
> +#'                        It is the source of variables mentioned in
>
> +#'                        'population_where', 'treatment_var', 'stratum_var' and 'covariate_var'.
>
>
> ⬇️ Suggested change
>
> -#'                        'population_where', 'treatment_var', 'stratum_var' and 'covariate_var'.
>
> +#'                        `population_where`, `treatment_var`, `stratum_var` and `covariate_var`.
>
>
> ------------------------------
>
> In R/tidy_population.R
> <https://github.com/elong0527/forestly/pull/12#discussion_r598040138>:
>
> >  #'
>
> -#' @param population_from The input population level data table. For example, "subject level information" from the table "adsl".
>
> -#' @param population_where Tells the function which rows of the table should be select, according to the value of certain column. For example, select subset where "ITTFL=='Y'.
>
> -#' @param treatment_var The function will create a new column called "treatment" based on the column of this parameter. For example, the "treatment" column will be equal to "TRT01A".
>
> -#' @param treatment_order Tells the function which rows of the table should be select, only if the values in "treatment" is in this parameter. It also provide the label names of the treatments after turning them into factors. For example, include rows which treatment = "Placebo" and treatment = "Xanomeline High Dose", and change the factor labels into "Placebo" and "MK9999".
>
> -#' @param stratum_var The function will create a new column called "stratum" based on this parameter.
>
> +#' @param population_from A data frame to obtain population level variables.
>
> +#'                        Typically an 'adsl' dataset.
>
> +#'                        It is the source of variables mentioned in
>
> +#'                        'population_where', 'treatment_var', 'stratum_var' and 'covariate_var'.
>
> +#' @param population_where A character string to define the criteria to select analysis population.
>
> +#' @param treatment_var  A character string to define the variable of new column called "treatment".
>
> +#' @param treatment_order A vector of character strings that tells the function which rows of the table should be select, only if the values in "treatment" is in this vector.
>
>
> ⬇️ Suggested change
>
> -#' @param treatment_order A vector of character strings that tells the function which rows of the table should be select, only if the values in "treatment" is in this vector.
>
> +#' @param treatment_order A vec [...]

2021-03-25 00:46 UTC, merged

2021-03-25 00:49 UTC, elong0527 commented
Thanks Yitao. You may review reference in #2 and #3 in preparing the work