modify js code to remove (All)
elong0527/forestly pull request #171
Opened 2023-04-27 23:23 UTC by wangben718

Now, `(All)` is removed. Default value is not defined.

2023-04-28 01:24 UTC, elong0527 requested changes

2023-04-28 01:24 UTC, elong0527 commented on R/ae_forestly.R
> +  random_id <- paste0("filter_ae_", sample(1:9999, 1))
Could we change to tmpfile? There is a chance to get issue by limited to 1-9999 when number of plot become large.

https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/tempfile

2023-04-28 01:24 UTC, elong0527 commented on inst/javascripts/filter_crosstalk.js
> +///[0].selectize.setValue("<%=default_param%>", false);
Is it because you did not add setValue?

2023-05-02 05:29 UTC, wangben718 commented on R/ae_forestly.R
> +  random_id <- paste0("filter_ae_", sample(1:9999, 1))
I am not using `tempfile()` since we need a prefix for ID used to search all the IDs in js code.

2023-05-03 15:30 UTC, fb-elong approved these changes

2023-05-03 15:33 UTC, elong0527 approved these changes

2023-05-03 18:12 UTC, merged