Sparkline error bar test
elong0527/forestly pull request #35
Opened 2021-07-14 20:14 UTC by mj719

error bar test

2021-07-15 14:49 UTC, elong0527 commented
Please double check the testing code, the `test-coverage` workflow shall pass before we merge. 

https://github.com/elong0527/forestly/pull/34/checks?check_run_id=3070542985

2021-07-26 19:39 UTC, wangben718 requested changes

2021-07-26 19:39 UTC, wangben718 commented on tests/testthat/test-sparkline_errorbar.R
> +
library(plotly)
library(ggplot2)

2021-07-26 19:39 UTC, wangben718 commented on tests/testthat/test-sparkline_errorbar.R
> +  expect_s3_class(tidy_observation(est = c(0,1,2),
replace `tidy_observation()` to `sparkline_errorbar()'

2021-07-26 19:39 UTC, wangben718 commented on tests/testthat/test-sparkline_errorbar.R
> +})
plotly_snap <- function(p){
  p_js <- plotly::plotly_json(p, jsonedit = FALSE)
  p_lst <- jsonlite::fromJSON(p_js)

  gsub(names(p_lst$visdat), "0000", as.character(p_lst))

}

test_that("sparkline_errorbar",{
  est <- c(0,1,2)
  lower <- c(-1, -2, -1)
  upper <- c(3, 5, 5)
  color <- c("red", "blue", "gold")
  temp1<-sparkline_errorbar(est,lower,upper,color)

  expect_snapshot_output(plotly_snap(temp1))
})

2021-07-26 20:04 UTC, closed without merging