upload rate0compare
elong0527/forestly pull request #47
Opened 2021-07-30 19:10 UTC by XDeng0921

2021-07-30 21:48 UTC, elong0527 requested changes
Thanks for working on the test. Please find my suggestions below.

2021-07-30 21:48 UTC, elong0527 commented on R/rate0compare.R
> +# adrs<-read_sas("//bardsar-test/mk7902-nsclc/prot008-ia1-dmc/dataanalysis/adrs.sas7bdat")
this example will not work. Please use data in this project to illustrate the work.

`@examples` is required. Please refer https://r-pkgs.org/r-cmd-check.html?q=examples#documentation

2021-07-30 21:48 UTC, elong0527 commented on R/rate0compare.R
> +  PI <- 3.14159265
let's use built in variable `pi`

2021-07-30 21:48 UTC, elong0527 commented on R/rate0compare.R
> +    count_data_long <- rs_data %>%dplyr::group_by_at("Treatment") %>%
`group_by_at` is a deprecated method. Please refer https://dplyr.tidyverse.org/reference/across.html

I would suggest to only use base R for this function. Refer this http://www.tinyverse.org/

2021-07-30 21:48 UTC, elong0527 commented on R/rate0compare.R
> +rate0compare <- function(Treatment, Response, Stratum, stratified=NULL, TRT_ord = c("Pembrolizumab+ Placebo","Pembrolizumab+ Ipilimumab"),
I would suggest a function input as below. 

`formula = response ~ treatment | stratum` can be used to reduce parameters. 
 `data` can be used similar to `lm`
`TRT_ord` can be defined by requiring `treatment` to be a vector. 
`stratified ` is not required. As long as "stratum` is provided, it performs stratified test. 

Please use lower cases for all function and variable name. Please refer https://style.tidyverse.org/syntax.html

```suggestion
rate_compare <- function(formula, 
                                          data,
                                          delta = 0, 
                                          weight_schema= c('ss','equal','cmh'),
                                          test = c('two.sided', 'left', 'right'),
                                          alpha=0.05, 
                                          bisection = 100, 
                                          eps=1e-06)

```

2021-07-30 21:48 UTC, elong0527 commented on R/rate0compare.R
> +      spread(key = Treatment, value = N) %>% rename(N1 =as.character(TRT_ord[2]), N0 = as.character(TRT_ord[1])) %>%
`spread` is a deprecated method, please refer https://tidyr.tidyverse.org/articles/pivot.html

2021-07-30 21:48 UTC, elong0527 commented on R/rate0compare.R
> +#' @param delta delta under the null
Let's refer this to document variables: https://style.tidyverse.org/documentation.html. For example

```suggestion
#' @param delta a numeric value to set the difference of two group under the null

```

2021-07-30 21:48 UTC, elong0527 commented on R/rate0compare.R
> +#
Please add the reference following proper style

```
Miettinen, O. and Nurminen, M: "Comparative Analysis of Two Rates", STATISTICS IN
MEDICINE, 4:213-226, 1985.
```

2021-08-01 20:44 UTC, XDeng0921 commented on R/rate0compare.R
> +#' stratified  MH TEST
Not sure whether we want to change to stratified MH TEST, since the function also allows the unstratified test.

2021-08-11 19:47 UTC, XDeng0921 commented on R/rate0compare.R
> +# adrs<-read_sas("//bardsar-test/mk7902-nsclc/prot008-ia1-dmc/dataanalysis/adrs.sas7bdat")
used simulation data for example.

2021-08-11 19:52 UTC, XDeng0921 commented on R/rate0compare.R
> +  PI <- 3.14159265
built in pi is used

2021-08-11 19:52 UTC, XDeng0921 commented on R/rate0compare.R
> +rate0compare <- function(Treatment, Response, Stratum, stratified=NULL, TRT_ord = c("Pembrolizumab+ Placebo","Pembrolizumab+ Ipilimumab"),
updated

2021-08-11 19:52 UTC, XDeng0921 commented on R/rate0compare.R
> +#
please check the style.

2021-08-12 18:03 UTC, XDeng0921 commented on vignettes/rate_compare.Rmd
> +```{r,collectcode=TRUE,echo=FALSE}
Those sas macros are in not R package, so it might give error when running this RMD file. Any solution? @elong0527

2021-08-16 17:24 UTC, elong0527 commented on vignettes/rate_compare.Rmd
> +```{r,collectcode=TRUE,echo=FALSE}
Just remove the `{r, ...}` part. 

```suggestion
```
```

2021-08-16 17:27 UTC, elong0527 commented on R/rate_compare.R
> +#' @export
always put `@export` at the last line

2021-08-16 20:18 UTC, XDeng0921 commented on vignettes/rate_compare.Rmd
> +```{r,collectcode=TRUE,echo=FALSE}
@elong0527 I might refer to wrong lines. I mean for lines 128-130 below, those sas macros are not in forestly package, would it matter?

2021-08-17 22:30 UTC, elong0527 commented on R/rate_compare.R
> +                    w = ifelse(rep(weight_schema=='equal',length(stratum)),1,ifelse(rep(weight_schema=='ss',length(stratum)),N/sum(N),(N0*N1/N)/sum(N0*N1/N))),
This line can be improved. Could you use `switch` function here?

2021-08-17 22:30 UTC, elong0527 commented on R/rate_compare.R
> +  stratum_var <- untangle.specials(terms(formula,specials="strata"),"strata",1)$vars
It is interesting you are using a function from `survival` package for a binary outcome. 

Could we consider other alternative function?

2021-08-17 22:30 UTC, elong0527 commented on R/rate_compare.R
> +    test_stat <- count_data %>%  dplyr::mutate(
try to make all variable name, argument name be lower cases and refer tidyverse style guide. 

https://style.tidyverse.org/syntax.html#object-names

2021-08-17 22:30 UTC, elong0527 commented on R/rate_compare.R
> +  BIroot<- function (f, a, b)
add comments to explain what is `f, a, b`

2021-08-17 22:30 UTC, elong0527 commented on R/rate_compare.R
> +        p = ifelse(p>(-1e-20) & p<0,
why do we need this part? 

If necessary, create a small function for this instead of copying in multiple place. 

Try to follow this suggestion:

https://r4ds.had.co.nz/functions.html#when-should-you-write-a-function

2021-08-19 17:10 UTC, XDeng0921 commented on R/rate_compare.R
> +  stratum <- mf[,attr(terms(formula,specials="strata"),"specials")$strata]
@elong0527 
+strata() in formula needs "survival" package. 
In your previous suggestion, to have format as response~treatment|stratum, "|" means condition on stratum in the convention language. I am not sure whether we want to use "|".
With +strata() format, it requires survival package.
Another option is to have formula as response~treatment, and add stratum= parameter. Let me know your thought.

2021-08-19 17:13 UTC, XDeng0921 commented on R/rate_compare.R
> +    pval <- switch(test,one.sided=ifelse(delta<=0, 1 - pnorm(z_score), pnorm(z_score)),two.sided=1 - pchisq(z_score^2,1))
ifelse is still used in some places through the function, which I feel is a convenient way. Let me know whether it is necessary to update.

2021-08-19 17:14 UTC, XDeng0921 commented on R/rate_compare.R
> +  z <- data.frame(r_diff,z_score, pval, ci[1],ci[2])
@elong0527 
I am not quite sure what utility function looks like here. Could you please provide some examples?

2021-08-19 20:23 UTC, XDeng0921 commented on vignettes/rate_compare.Rmd
>        collapsed: yes
please ignore rmd changes. i ddint know you reformatted it and committed back to my version.
so i changed back.

2021-08-20 02:46 UTC, elong0527 commented on R/rate_compare.R
> +    pval <- switch(test,one.sided=ifelse(delta<=0, 1 - pnorm(z_score), pnorm(z_score)),two.sided=1 - pchisq(z_score^2,1))
Using ifelse is ok. Thanks! Just avoid multiple layer of `ifelse`

2021-08-20 02:49 UTC, elong0527 commented on R/rate_compare.R
> +  stratum <- mf[,attr(terms(formula,specials="strata"),"specials")$strata]
Thanks for the clarification. Yeah, I just notice `strata()` is an unique item for Cox model. 

I am OK with either using `|` or add `stratum` parameter. Using `stratum=` parameter seems easier to understand as `|` has different meaning in different packages.

2021-09-03 00:25 UTC, elong0527 commented
Let's merge this PR as it already in a relative good shape. Some errors in the CI/CD is related to other functions that needs to be addressed later. (e.g. `ae_interested`)

One trick:

- Roxygen2 support Rmarkdown syntax

2021-09-03 00:25 UTC, merged